### ISSUE TITLE
该 loader 怎么安装和配置呢？

### ISSUE THREAD

**Issue by songxingguo** [verymuch/webpack-html-include-loader#1]
老哥你是不是忘记写，如何使用这个安装和配置这个 loader 了呢？

**Comment by verymuch** [comment]
我明天补充一下，现在没电脑了




在2020年06月17日 22:55，宋兴国 写道：

老哥你是不是忘记写，如何使用这个安装和配置这个 loader 了呢？

**Comment by verymuch** [comment]
感谢反馈 😂




在2020年06月17日 23:53，verymuch(高峰) 写道：
我明天补充一下，现在没电脑了




在2020年06月17日 22:55，宋兴国 写道：

老哥你是不是忘记写，如何使用这个安装和配置这个 loader 了呢？

**Comment by verymuch** [comment]
感谢反馈，已更新安装与使用文档，顺便加上了[开发思路详解](https://github.com/verymuch/blog/issues/13)，有兴趣欢迎查看。
